backend/modules/ventas/models/PedidoDetalle.php
<?php

namespace frontend\modules\ventas\models;

use Yii;

/**
 * This is the model class for table "pedido_detalle".
 *
 * @property integer $id
 * @property integer $producto_id
 * @property integer $pedido_id
 * @property integer $cantidad
 *
 * @property Pedido $pedido
 * @property Producto $producto
 */
class PedidoDetalle extends \yii\db\ActiveRecord
{public $my_attribute='9001';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pedido_detalle';
        
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['producto_id', 'pedido_id', 'cantidad'], 'required'],
            [['producto_id', 'pedido_id', 'cantidad'], 'integer'],
            [['pedido_id'], 'exist', 'skipOnError' => true, 'targetClass' => Pedido::className(), 'targetAttribute' => ['pedido_id' => 'id']],
          //  [['producto_id'], 'exist', 'skipOnError' => true, 'targetClass' => Producto::className(), 'targetAttribute' => ['producto_id' => 'id']],
            
            ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'producto_id' => 'ID Producto',
            'pedido_id' => 'ID Pedido',
            'cantidad' => 'Cantidad',
            
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
   /* public function getPedido()
    {
        return $this->hasOne(Pedido::className(), ['id' => 'pedido_id']);
    }*/

    /**
     * @return \yii\db\ActiveQuery
     */
   /* public function getProducto()
    {
        return $this->hasOne(Producto::className(), ['id' => 'producto_id']);
    }*/
}

backend/modules/ventas/controllers/PedidoDetalleController.php
<?php

namespace frontend\modules\ventas\controllers;

use Yii;
use frontend\modules\ventas\models\PedidoDetalle;
use frontend\modules\ventas\models\search\PedidoDetalleSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\HtmlHelpers;
use yii\web\Response;
use yii\widgets\ActiveForm;


/**
 * PedidoDetalleController implements the CRUD actions for PedidoDetalle model.
 */
class PedidoDetalleController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PedidoDetalle models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PedidoDetalleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PedidoDetalle model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PedidoDetalle model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PedidoDetalle();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    
        public function actionCreate_2($submit = false)
    {
        $model = new PedidoDetalle();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()) && $submit == false) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return ActiveForm::validate($model);
    }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['message' => '¡Agregado...!',
                   ];
        } else {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $this->renderAjax('create_2', [
                'model' => $model,
            ]);
        }
    }
 
    public function actionCreate_1($submit = false)
{   
    $model = new PedidoDetalle();

 
    if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()) && $submit == false) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return ActiveForm::validate($model);
    }
 
    if ($model->load(Yii::$app->request->post())) {
        if ($model->save()) {
            $model->refresh();
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['message' => '¡Éxito!',
                    ];
        } else {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }
 
    return $this->renderAjax('create_1', [
        'model' => $model,
    ]);
        
}

    /**
     * Updates an existing PedidoDetalle model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
    
        public function actionUpdate_2($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['catalogo-producto/realizarcomprat']);
        } else {
            return $this->render('update_2', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing PedidoDetalle model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
        public function actionDelete2($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['catalogo-producto/realizarcompra']);
    }

    /**
     * Finds the PedidoDetalle model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PedidoDetalle the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PedidoDetalle::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    public function actionUserList($q = null, $id = null) {
    return HtmlHelpers::sugestionList('producto_id', 'catalogo_producto', 'CatalogoProducto', $q, $id);
}
}

backend/modules/ventas/views/pedido-detalle/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\web\JsExpression;
use kartik\widgets\Select2;
use frontend\modules\ventas\models\Pedido;
use yii\helpers\ArrayHelper;
use frontend\modules\ventas\models\PedidoDetalle

/* @var $this yii\web\View */
/* @var $model frontend\modules\ventas\models\PedidoDetalle */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="pedido-detalle-form">

    <?php $form = ActiveForm::begin(); ?>
    
    <?= $form->field($model, 'producto_id') ?>
    
   <?= $form->field($model, 'pedido_id')->dropDownList(ArrayHelper::map(PedidoDetalle::find()->where(['pedido_id'=>9001])->all()
           , 'pedido_id', 'pedido_id'))
?>

    <?= $form->field($model, 'cantidad')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Agregar' : 'Modificar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/ventas/views/pedido-detalle/_form_1.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\web\JsExpression;
use kartik\widgets\Select2;
use yii\helpers\ArrayHelper;
use frontend\modules\ventas\models\Pedido;
use frontend\modules\ventas\models\PedidoDetalle;
use yii\db\Query;
$connection = \Yii::$app->db;
/* @var $this yii\web\View */
/* @var $model frontend\modules\ventas\models\PedidoDetalle */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pedido-detalle-form-1">

    <?php //$form = ActiveForm::begin(); ?>
    
    <?php $form = ActiveForm::begin([
    'id' => 'pedido-detalle-form-1',
    'enableAjaxValidation' => true,
    'enableClientScript' => true,
    'enableClientValidation' => true,
]); ?>



<?=   Html::activeLabel($model, "producto_id")
?>
<?= 
Select2::widget([
    'model' => $model,
    'attribute' => "producto_id",
    'initValueText' => '', // set the initial display text
    'options' => ['placeholder' => 'Ingrese codigo...'],
    'pluginOptions' => [
        'allowClear' => true,
        'minimumInputLength' => 2,
        'ajax' => [
            'url' => Url::to(['pedido-detalle/user-list']),
            'dataType' => 'json',
            'data' => new JsExpression('function(params) { return {q:params.term}; }')
        ],
        'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
        'templateResult' => new JsExpression('function(pedido_detalle) { return pedido_detalle.text; }'),
        'templateSelection' => new JsExpression('function (pedido_detalle) { return pedido_detalle.text; }'),
    ],
])  
  
?>
  </br> 


    <?php
 $sql='SELECT
      id
    FROM
      pedido
    WHERE
     pedido.tipo_pedido_id = "800"
    ORDER BY
      id DESC
    LIMIT 1;
';
    
     $model1=$connection->createCommand($sql)->queryOne();
            ?>
   <?= $form->field($model, 'pedido_id')->dropDownList(ArrayHelper::map(Pedido::find()->where(['id'=>[$model1['id']]])->all()
           , 'id', 'id'))
?>
  
    
 <?= $form->field($model, 'cantidad')->textInput() ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Agregar' : 'Modificar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

      <?php
$this->registerJs('
    // obtener la id del formulario y establecer el manejador de eventos
        $("form#pedido-detalle-form-1").on("beforeSubmit", function(e) {
            var form = $(this);
            $.post(
                form.attr("action")+"&submit=true",
                form.serialize()
            )
            .done(function(result) {
                form.parent().html(result.message);
                $.pjax.reload({container:"#pedido-detalle-grid"});
            });
            return false;
        }).on("submit", function(e){
            e.preventDefault();
            e.stopImmediatePropagation();
            return false;
        });
    ');
?>
    <?php
$this->registerJs('
$("#pedido-detalle-pedido_id").on("select2:unselect", function (e) {
        $("#pedido-detalle-pedido_id-error").html( "pedido ID no puede estar vacío." );
        $("#pedido-detalle-pedido_id-container").removeClass( "has-success" ).addClass( "has-error" );
    });
    $("#pedido-detalle-pedido_id").on("select2:select", function (e) {
        $("#pedido-detalle-pedido_id-error").html( "" );
        $("#pedido-detalle-pedido_id-container").removeClass( "has-error" ).addClass( "has-success" );
    });
');
?>
</div>

backend/modules/ventas/views/pedido-detalle/_form_2.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\web\JsExpression;
use kartik\widgets\Select2;
use frontend\modules\ventas\models\Pedido;
use yii\helpers\ArrayHelper;
use frontend\modules\ventas\models\PedidoDetalle;
use yii\jui\DatePicker;
use yii\db\Query;
$connection = \Yii::$app->db;

/* @var $this yii\web\View */
/* @var $model frontend\modules\ventas\models\PedidoDetalle */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="pedido-detalle-form-2">

    <?php $form = ActiveForm::begin([    
            'id' => 'pedido-detalle-form-2',
    'enableAjaxValidation' => true,
    'enableClientScript' => true,
    'enableClientValidation' => true,
]); ?>
  
    
<?=   Html::activeLabel($model, "producto_id")
?>
<?= 
Select2::widget([
    'model' => $model,
    'attribute' => "producto_id",
    'initValueText' => '', // set the initial display text
    'options' => ['placeholder' => 'Ingrese codigo...'],
    'pluginOptions' => [
        'allowClear' => true,
        'minimumInputLength' => 2,
        'ajax' => [
            'url' => Url::to(['pedido-detalle/user-list']),
            'dataType' => 'json',
            'data' => new JsExpression('function(params) { return {q:params.term}; }')
        ],
        'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
        'templateResult' => new JsExpression('function(pedido_detalle) { return pedido_detalle.text; }'),
        'templateSelection' => new JsExpression('function (pedido_detalle) { return pedido_detalle.text; }'),
    ],
])  
  
?>
    <?php
 $sql='SELECT
      id
    FROM
      pedido
    WHERE
     pedido.tipo_pedido_id = "900"
    ORDER BY
      id desc
    LIMIT 1;
';
    
     $model1=$connection->createCommand($sql)->queryOne();
            ?>
   <?= $form->field($model, 'pedido_id')->dropDownList(ArrayHelper::map(Pedido::find()->where(['id'=>[$model1['id']]])->all()
           , 'id', 'id'))
?>

    <?= $form->field($model, 'cantidad')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Agregar.' : 'Actualizar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    
  <?php
$this->registerJs('
    // obtener la id del formulario y establecer el manejador de eventos
        $("form#pedido-detalle-form-2").on("beforeSubmit", function(e) {
            var form = $(this);
            $.post(
                form.attr("action")+"&submit=true",
                form.serialize()
            )
            .done(function(result) {
                form.parent().html(result.message);
                $.pjax.reload({container:"#pedido-detalle-grid"});
            });
            return false;
        }).on("submit", function(e){
            e.preventDefault();
            e.stopImmediatePropagation();
            return false;
        });
    ');
?> 

</div>

backend/modules/ventas/views/pedido-detalle/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\modules\ventas\models\search\PedidoDetalleSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pedido-detalle-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'producto_id') ?>

    <?= $form->field($model, 'pedido_id') ?>

    <?= $form->field($model, 'cantidad') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/ventas/views/pedido-detalle/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\modules\ventas\models\PedidoDetalle */

$this->title = 'Agregar Pedido';
$this->params['breadcrumbs'][] = ['label' => 'Mis Pedidos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pedido-detalle-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/ventas/views/pedido-detalle/create_1.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\modules\ventas\models\PedidoDetalle */

$this->title = 'Agregar Pedido';
$this->params['breadcrumbs'][] = ['label' => 'Pedido Detalles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pedido-detalle-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form_1', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/ventas/views/pedido-detalle/create_2.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\modules\ventas\models\PedidoDetalle */

$this->title = 'Venta';
$this->params['breadcrumbs'][] = ['label' => 'Pedido Detalles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pedido-detalle-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form_2', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/ventas/views/pedido-detalle/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use frontend\modules\ventas\models\CatalogoProducto;
use yii\helpers\ArrayHelper;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $searchModel frontend\modules\ventas\models\search\PedidoDetalleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Mis Pedidos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pedido-detalle-index">

    <h1 style="color:#00b3ee"  align='center'><?= Html::encode($this->title) ?></h1>
   <hr style="height: 2px ; background: #0097cf"><br>
 <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p align='center'>
   <?= Html::a('Agregar Pedidos', '#', [
            'id' => 'activity-index-link',
            'class' => 'btn btn-success',
            'data-toggle' => 'modal',
            'data-target' => '#modal',
            'data-url' => Url::to(['create_1']),
            'data-pjax' => '0',
        ]); ?>
    </p>
    <?php Pjax::begin() ?>
   <?=  GridView::widget([
       'id' => 'pedido-detalle-grid',
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            //'producto_id',
            ['attribute'=>'producto_id',
                'value'=>function($model){
                    $catalogoproducto = CatalogoProducto::findOne($model->producto_id);
                    return $catalogoproducto->nomcatprod;
                },
                   //'filter' => ArrayHelper::map(CatalogoProducto::find()->all(),'id','nomcatprod'),
            ],
            'pedido_id',
            'cantidad',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]);  ?> 
    <?php Pjax::end() ?>

 <?php    
     $this->registerJs(
    "$(document).on('click', '#activity-index-link', (function() {
        $.get(
            $(this).data('url'),
            function (data) {
                $('.modal-body').html(data);
                $('#modal').modal();
            }
        );
    }));"
); ?>
     <?php
Modal::begin([
    'options'=>[
        'tabindex'=>'false'
    ],
    'id' => 'modal',
    'header' => '<h4 class="modal-title">Complete</h4>',
    'footer' => '<a href="#" class="btn btn-primary" data-dismiss="modal">Cerrar</a>',

    ]);
 
echo "<div class='well'></div>";
 
Modal::end();
?>
 
</div>

backend/modules/ventas/views/pedido-detalle/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\modules\ventas\models\PedidoDetalle */

$this->title = 'Modificar Pedido: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Pedido Detalles', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Modificar';
?>
<div class="pedido-detalle-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/ventas/views/pedido-detalle/update_2.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\modules\ventas\models\PedidoDetalle */

$this->title = 'Modificar Producto de Venta: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Catalogo Productos', 'url' => ['catalogo-productos/index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Modificar';
?>
<div class="pedido-detalle-update-2">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/ventas/views/pedido-detalle/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\modules\ventas\models\PedidoDetalle */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Pedido Detalles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pedido-detalle-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Modificar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'producto_id',
            'pedido_id',
            'cantidad',
        ],
    ]) ?>

</div>