backend/modules/ventas/models/CatalogoProducto.php
<?php

namespace frontend\modules\ventas\models;

use Yii;

/**
 * This is the model class for table "catalogo_producto".
 *
 * @property integer $id
 * @property integer $catalogo_id
 * @property integer $campana_id
 * @property integer $producto_id
 * @property integer $incentivo_id
 * @property integer $estado
 * @property Campana $campana
 * @property Catalogo $catalogo
 * @property Incentivo $incentivo
 * @property Producto $producto
 * @property integer $unidad
 * @property string $precio
 * @property string $precio_vta
 * @property integer $descuento
 */
class CatalogoProducto extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'catalogo_producto';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
           /* [['catalogo_id', 'campana_id', 'producto_id', 'incentivo_id', 'nomcatprod', 'precatprod', 'tamcatprod', 'stocatprod'], 'required'],
            [['catalogo_id', 'campana_id', 'producto_id', 'incentivo_id', 'estado', 'tamcatprod', 'stocatprod'], 'integer'],
            [['precatprod'], 'number'],
            [['descripcion'], 'string', 'max' => 255],
            [['nomcatprod'], 'string', 'max' => 45],*/
            
            
           // [['campana_id'], 'exist', 'skipOnError' => true, 'targetClass' => Campana::className(), 'targetAttribute' => ['campana_id' => 'id']],
           // [['catalogo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Catalogo::className(), 'targetAttribute' => ['catalogo_id' => 'id']],
           // [['incentivo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Incentivo::className(), 'targetAttribute' => ['incentivo_id' => 'id']],
           // [['producto_id'], 'exist', 'skipOnError' => true, 'targetClass' => Producto::className(), 'targetAttribute' => ['producto_id' => 'id']],
             [['catalogo_id', 'campana_id', 'producto_id', 'incentivo_id'], 'required'],
            [['catalogo_id', 'campana_id', 'producto_id', 'incentivo_id', 'estado'], 'integer'],
             [['unidad', 'descuento'], 'integer'],
            [['precio', 'precio_vta'], 'number'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
        //    'catalogo_id' => 'Catalogo ID',
        //    'campana_id' => 'Campana ID',
         //   'producto_id' => 'Producto ID',
         //   'incentivo_id' => 'Incentivo ID',
            'descripcion' => 'Descripcion',
            'estado' => 'Estado',
            'unidad' => 'Unidad',
            'precio' => 'Precio',
            'precio_vta' => 'Precio Vta',
            'descuento' => 'Descuento',
           /* 'nomcatprod' => 'Nomcatprod',
            'precatprod' => 'Precatprod',
            'tamcatprod' => 'Tamcatprod',
            'stocatprod' => 'Stocatprod',*/
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
   /* public function getCampana()
    {
        return $this->hasOne(Campana::className(), ['id' => 'campana_id']);
    }*/

    /**
     * @return \yii\db\ActiveQuery
     */
  /*  public function getCatalogo()
    {
        return $this->hasOne(Catalogo::className(), ['id' => 'catalogo_id']);
    }
*/
    /**
     * @return \yii\db\ActiveQuery
     */
  /*  public function getIncentivo()
    {
        return $this->hasOne(Incentivo::className(), ['id' => 'incentivo_id']);
    }*/

    /**
     * @return \yii\db\ActiveQuery
     */
  /*  public function getProducto()
    {
        return $this->hasOne(Producto::className(), ['id' => 'producto_id']);
    }*/
}

backend/modules/ventas/controllers/CatalogoProductoController.php
<?php

namespace frontend\modules\ventas\controllers;

use Yii;
use frontend\modules\ventas\models\CatalogoProducto;
use frontend\modules\ventas\models\search\CatalogoProductoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use frontend\modules\ventas\models\PedidoDetalle;

/**
 * CatalogoProductoController implements the CRUD actions for CatalogoProducto model.
 */
class CatalogoProductoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all CatalogoProducto models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CatalogoProductoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single CatalogoProducto model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CatalogoProducto model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new CatalogoProducto();
        $tipopedido = PedidoDetalle::find()->all();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'tipopedido' => $tipopedido,
            ]);
        }
    }

    /**
     * Updates an existing CatalogoProducto model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id){
        $model = $this->findModel($id);
        $tipopedido = PedidoDetalle::find()->all();

        $model->ped = \yii\helpers\ArrayHelper::getColumn(
            $model->getRolOperaciones()->asArray()->all(),
            'operacion_id'
        );

        if ($model->load(Yii::$app->request->post())) {
            if (!isset($_POST['Rol']['operaciones'])) {
                $model->operaciones = [];
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
                'tipoOperaciones' => $tipoOperaciones
            ]);
        }
    }

    /**
     * Deletes an existing CatalogoProducto model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CatalogoProducto model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CatalogoProducto the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CatalogoProducto::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    public function actionRealizarcomprat(){
        return $this->render('realizarcompraT');
    }
    public function actionFacturatienda(){
        return $this->render('facturatienda');
    }
    public function actionBoletatienda(){
        return $this->render('boletatienda');
    }
}

backend/modules/ventas/controllers/InterlocutorComercialController.php
<?php

namespace frontend\modules\ventas\controllers;

use Yii;
use frontend\modules\ventas\models\InterlocutorComercial;
use frontend\modules\ventas\models\search\InterlocutorComercialSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * InterlocutorComercialController implements the CRUD actions for InterlocutorComercial model.
 */
class InterlocutorComercialController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all InterlocutorComercial models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new InterlocutorComercialSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single InterlocutorComercial model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new InterlocutorComercial model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new InterlocutorComercial();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing InterlocutorComercial model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing InterlocutorComercial model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the InterlocutorComercial model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return InterlocutorComercial the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = InterlocutorComercial::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/ventas/controllers/PedidoDetalleController.php
<?php

namespace frontend\modules\ventas\controllers;

use Yii;
use frontend\modules\ventas\models\PedidoDetalle;
use frontend\modules\ventas\models\search\PedidoDetalleSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\HtmlHelpers;
use yii\web\Response;
use yii\widgets\ActiveForm;


/**
 * PedidoDetalleController implements the CRUD actions for PedidoDetalle model.
 */
class PedidoDetalleController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PedidoDetalle models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PedidoDetalleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PedidoDetalle model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PedidoDetalle model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PedidoDetalle();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    
        public function actionCreate_2($submit = false)
    {
        $model = new PedidoDetalle();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()) && $submit == false) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return ActiveForm::validate($model);
    }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['message' => '¡Agregado...!',
                   ];
        } else {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $this->renderAjax('create_2', [
                'model' => $model,
            ]);
        }
    }
 
    public function actionCreate_1($submit = false)
{   
    $model = new PedidoDetalle();

 
    if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()) && $submit == false) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return ActiveForm::validate($model);
    }
 
    if ($model->load(Yii::$app->request->post())) {
        if ($model->save()) {
            $model->refresh();
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['message' => '¡Éxito!',
                    ];
        } else {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }
 
    return $this->renderAjax('create_1', [
        'model' => $model,
    ]);
        
}

    /**
     * Updates an existing PedidoDetalle model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
    
        public function actionUpdate_2($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['catalogo-producto/realizarcomprat']);
        } else {
            return $this->render('update_2', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing PedidoDetalle model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
        public function actionDelete2($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['catalogo-producto/realizarcompra']);
    }

    /**
     * Finds the PedidoDetalle model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PedidoDetalle the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PedidoDetalle::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    public function actionUserList($q = null, $id = null) {
    return HtmlHelpers::sugestionList('producto_id', 'catalogo_producto', 'CatalogoProducto', $q, $id);
}
}

backend/modules/ventas/views/catalogo-producto/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\modules\ventas\models\CatalogoProducto */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="catalogo-producto-form">

    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'producto_id')->textInput() ?>
    
    <?= $form->field($model, 'nomcatprod')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'precatprod')->textInput() ?>

    <?= $form->field($model, 'tamcatprod')->textInput() ?>

    <?= $form->field($model, 'stocatprod')->textInput() ?> 
    
    <?= $form->field($model, 'catalogo_id')->textInput() ?>

    <?= $form->field($model, 'campana_id')->textInput() ?>

    <?= $form->field($model, 'incentivo_id')->textInput() ?>

    <?= $form->field($model, 'descripcion')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'estado')->textInput() ?>



    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/ventas/views/catalogo-producto/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use yii\widgets\Pjax;
use frontend\modules\ventas\models\Producto;
use frontend\modules\ventas\models\Stock;
use yii\web\JsExpression;
use yii\db\Query;
$connection = \Yii::$app->db;

/* @var $this yii\web\View */
/* @var $searchModel frontend\modules\ventas\models\search\CatalogoProductoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Catalogo Productos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="catalogo-producto-index">

    <h1 style="color:#00b3ee"  align='center'><?= Html::encode($this->title) ?></h1>
    <hr style="height: 2px ; background: #0097cf"><br>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Buscar Consultora', ['interlocutor-comercial/index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Agregar Producto a Venta', '#', [
            'id' => 'activity-index-link',
            'class' => 'btn btn-success',
            'data-toggle' => 'modal',
            'data-target' => '#modal',
            'data-url' => Url::to(['pedido-detalle/create_2']),
            'data-pjax' => '0',
        ]); ?>
       <?= Html::a('Ver Productos de la Venta', ['realizarcomprat'], ['class' => 'btn btn-success']) ?>    
        
    </p>
    <?php //Pjax::begin() ?>
    <?= GridView::widget([
        'id' => 'pedido-detalle-grid',
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
             
          //  'id',
           // 'catalogo_id:text:catalogo',
            //'campana_id',
            'producto_id:text:Codigo Producto',
            //'incentivo_id',

            /* 'nomcatprod:text:Nombre',
             'precatprod:text:Precio',
             'tamcatprod:text:Tamaño',
             'stocatprod:text:Stock',*/
            'unidad',
            'precio',
            'precio_vta',
            'descuento',
            
            
          /*  ['attribute'=>'nombre',
                'value'=>function($model){
                    $catalogoproducto = Producto::findOne($model->id);
                    return $catalogoproducto->nombre;
                },
                   //'filter' => ArrayHelper::map(CatalogoProducto::find()->all(),'id','nomcatprod'),
            ],
            ['attribute'=>'precio',
                'value'=>function($model){
                    $catalogoproducto = Producto::findOne($model->id);
                    return $catalogoproducto->precio;
                },
                   //'filter' => ArrayHelper::map(CatalogoProducto::find()->all(),'id','nomcatprod'),
            ],
            ['attribute'=>'precio venta',
                'value'=>function($model){
                    $catalogoproducto = Producto::findOne($model->id);
                    return $catalogoproducto->precio_vta;
                },*/
                   //'filter' => ArrayHelper::map(CatalogoProducto::find()->all(),'id','nomcatprod'),
            //],
           /* ['attribute'=>'stock',
                'value'=>function($model){
                    $catalogoproducto = Stock::findOne($model->id);
                    return $catalogoproducto->stock;
                },
                   //'filter' => ArrayHelper::map(CatalogoProducto::find()->all(),'id','nomcatprod'),
            ],*/
           // ['class' => 'yii\grid\ActionColumn'],
                                    'descripcion',
             'estado',  
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}',
                'buttons' => [
                    'view' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-zoom-in"></span>', $url, [
                        ]);
                    },
            ]],
              
            ['class' => 'yii\grid\CheckboxColumn'],
                            
         /*  [
            'class'  => '\yii\grid\CheckboxColumn',
            'checkboxOptions' => [
               'class' => 'simple'
            ]
            ],*/
                            
        ],

    ]); ?>
    
    
    <?php
$this->registerJs(
    "$(document).on('click', '#activity-index-link', (function() {
        $.get(
            $(this).data('url'),
            function (data) {
                $('.modal-body').html(data);
                $('#modal').modal();
            }
        );
    }));"
); ?>
 
<?php
Modal::begin([
    'options'=>[
        'tabindex'=>'false'
    ],
    'id' => 'modal',
    'header' => '<h4 class="modal-title">Complete</h4>',
    'footer' => '<a href="#" class="btn btn-primary" data-dismiss="modal">Cerrar</a>',
]);
 
echo "<div class='well'></div>";
 
Modal::end();
?>
   <?php //<?= 
      //  Html::button('<i class="glyphicon glyphicon-download-alt"></i><span>   Filter Rows Select</span>',
     //   ['type'=>'button', 'class'=>'btn btn-success',
    //        'onclick'=>'var keys = $("#kv-grid").yiiGridView("getSelectedRows").length'
   // ])?>
</div>

backend/modules/ventas/views/catalogo-producto/realizarcompraT.php
<?php
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\grid\GridView;
use frontend\modules\ventas\models\PedidoDetalle;
use frontend\modules\ventas\models\Pedido;
use app\models;
use yii\db\Query;
$connection = \Yii::$app->db;
$tot=0;
$this->title = 'Realizar Venta';
$this->params['breadcrumbs'][] = ['label' => 'Catalogo Productos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
//$this->params ['breadcrumbs'][] = $this->title
?>

<h2><div style="color: #00b3ee" align='center'> VENDER PRODUCTOS</div></h2><br>
<hr style="height: 2px ; background: #0097cf">
<br>
<h2><div align='center'> Productos en la lista de venta:</div></h2><br>
<br>
<table class='table table-striped'>
    
    <tr>
        <th>Codigo</th>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Cantidad</th>
        <th></th>
        <th></th>
    </tr>
    <?php $table = new PedidoDetalle();
    $sql='select pedido_detalle.id as id,pedido_detalle.producto_id as producto_id, producto.nombre as nombre, catalogo_producto.precio_vta as precio_vta,  pedido_detalle.cantidad as cantidad from pedido_detalle, producto,catalogo_producto where pedido_detalle.pedido_id=9001 and pedido_detalle.producto_id=producto.id and catalogo_producto.producto_id=producto.id ;
';
    
    $model=$connection->createCommand($sql)->queryAll();
    //$model =Yii::app()->db->createCommand('select * from pedido_detalle')->queryAll();
   // $model = $table->find()->select('pedido_detalle.producto_id as producto_id, producto.nombre, pedido_detalle.cantidad') 
            //->from('pedido_detalle, producto')->where('pedido_detalle.pedido_id=9001 and producto.id=pedido_detalle.producto_id ')->all();
    //$model = $table->find()->where(['id'=>(['codigo'=>'1001'])])->all();//a
    ?>
    <?php foreach($model as $row): ?>
    <tr>
        
        <td><?= $row['producto_id']?></td>
        <td><?= $row['nombre'] ?></td>
        <td><?= $row['precio_vta'] ?></td>
        <td><?= $row['cantidad'] ?></td>
        <td><a class="btn btn-primary" href="
    <?= Url::toRoute(['pedido-detalle/update_2', 'id' => $row['id']])
    ?>">
                <span class="glyphicon glyphicon-edit"></span>
            </a></td>
      <td><?= Html::a('<span class="glyphicon glyphicon-trash"></span>', ['pedido-detalle/delete2', 'id' => $row['id']],
              [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Esta seguro de eliminar?',
                'method' => 'post',
            ],
        ]) ?></td>
    </tr>
    <?php endforeach ?>
    
    <?php    foreach ($model as $value) {
        $tot=$tot+($value['precio_vta']*$value['cantidad']);
    } 
    ?>
    
</table>
<div align='right'><b>TOTAL: S/.</b>  <?= $tot?> </div>
<hr style="height: 1px ; background: black">
<a class="btn btn-success" href="
    <?= Url::toRoute('boletatienda')
    ?>"> Finalizar con Boleta </a>
<a class="btn btn-success" href="
    <?= Url::toRoute('facturatienda')
    ?>"> Finalizar con Factura </a> 
<?= Html::submitInput('Cancelar',['class'=>'btn btn-alert ']) ?>

backend/modules/ventas/views/catalogo-producto/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use yii\bootstrap\Modal;
/* @var $this yii\web\View */
/* @var $model frontend\modules\ventas\models\CatalogoProducto */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Catalogo Productos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="catalogo-producto-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <p>
        <?= Html::a('Agregar a Pedido', '#', [
            'id' => 'activity-index-link',
            'class' => 'btn btn-success',
            'data-toggle' => 'modal',
            'data-target' => '#modal',
            'data-url' => Url::to(['pedido-detalle/create']),
            'data-pjax' => '0',
        ]); ?>
    <?php
$this->registerJs(
    "$(document).on('click', '#activity-index-link', (function() {
        $.get(
            $(this).data('url'),
            function (data) {
                $('.modal-body').html(data);
                $('#modal').modal();
            }
        );
    }));"
); ?>
 
<?php
Modal::begin([
    'id' => 'modal',
    'header' => '<h4 class="modal-title">Complete</h4>',
    'footer' => '<a href="#" class="btn btn-primary" data-dismiss="modal">Cerrar</a>',
]);
 
echo "<div class='well'></div>";
 
Modal::end();
?>
        
        
        
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'catalogo_id',
            'campana_id',
            'producto_id',
            'incentivo_id',
            'descripcion',
            'estado',
            'unidad',
            'precio',
            'precio_vta',
            'descuento',
        ],
    ]) ?>

 

</div>